server:
  port: 9003

#Eureka配置
eureka:
  client:
    register-with-eureka: false  #不向eureka注册自己
    service-url:
      #做集群需要关联集群的eureka服务器的地址,其实端口号都应该是7001，
      #关联的只是服务器地址，这里因为只有一台电脑，就用了端口号代替
      defaultZone: http://127.0.0.1:7001/eureka/

      #常见错误
      #参考文档博客园 https://www.cnblogs.com/cangqinglang/p/11704475.html
ribbon:
  ConnectTimeout: 100000 # ribbon链接超时时长
  ReadTimeout: 100000 # ribbon读取超时时间长
  eureka:
    enabled: true

spring:
  thymeleaf:
    mode: LEGACYHTML5




